[build-system]
requires = ["uv_build >= 0.12.0, <0.13.0"]
build-backend = "uv_build"

[project]
name = "pytest_circleci_coverage"
version = "0.2.0"
description = " Pytest plugin that works with pytest-cov to generate coverage data for CircleCI's Smarter Testing"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Testing"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "coverage>=7.10",
    "import-deps>=0.5.1",
]

[project.urls]
Homepage = "https://github.com/CircleCI-Public/smarter-testing-plugins"
Issues = "https://github.com/CircleCI-Public/smarter-testing-plugins/issues"

[project.entry-points.pytest11]
pytest_circleci_coverage = "pytest_circleci_coverage"
